### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by KumaNNN** [hexojs/hexo-generator-sitemap#107]
在`_config.yml`中的有些配置项目，不知道是什么意思？ 好像在源码中也未实现
```
sitemap:
  tags: true
  categories: true
```

----

What do you mean by some configuration items in `_config.yml` ? It seems that it is not implemented in the source code
```
sitemap:
  tags: true
  categories: true
```

**Comment by stevenjoezhang** [comment]
> What do you mean by some configuration items in `_config.yml` ?

Please read README.md before submitting issues, thanks!
https://github.com/hexojs/hexo-generator-sitemap#options

> It seems that it is not implemented in the source code

And you can use GitHub's search function to find what you want
https://github.com/hexojs/hexo-generator-sitemap/search?q=tags&unscoped_q=tags
https://github.com/hexojs/hexo-generator-sitemap/search?q=categories&unscoped_q=categories
