### ISSUE TITLE
page 页面URL格式问题

### ISSUE THREAD

**Issue by seozed** [hexojs/hexo-generator-sitemap#13]
如果我的页面正常访问的URL是这样的：`domain.com/about`，在生成的`sitemap.xml`里，它导出的URL格式就变成了这样：`domain.com/about/index.html`，这样的话，对爬虫会造成困扰。
因为`domain.com/about`，`domain.com/about/index.html` 对爬虫来说是两个页面，爬虫会分别抓取这两个页面，对爬虫来说是一种资源浪费，会造成重复收录。

参考我的sitemap:http://mazih.com/sitemap.xml

**Comment by leesei** [comment]
https://moz.com/learn/seo/canonicalization
https://support.google.com/webmasters/answer/139066?hl=en

I think we could use permalink as the canonical URL (in header and sitemap).
And I think the one without `index.html` is better.

**Comment by pyyzcwg2833** [comment]
@seozed 我对插件源码进行了修改，修复了这个问题
[hexo-generator-sitemap](https://github.com/pyyzcwg2833/hexo-generator-sitemap)

**Comment by seozed** [comment]
great!
