### ISSUE TITLE
无法提交 Google search，显示无法获取

### ISSUE THREAD

**Issue by Drun1baby** [hexojs/hexo-generator-sitemap#143]

**Comment by Drun1baby** [comment]
![Snipaste_2022-05-23_16-46-54](https://user-images.githubusercontent.com/75228348/169780813-e0b19ae0-f15c-4ad6-b5e4-3899a34d47c1.png)
使用的 sitemap 是用插件自动生成的，版本也是正确的

**Comment by Drun1baby** [comment]
![Uploading 1.png…]()

**Comment by Drun1baby** [comment]
![1](https://user-images.githubusercontent.com/75228348/169781022-196e8bfc-e28b-46e7-bc5a-8f8b117ac782.png)
报错如图所示

**Comment by uiolee** [comment]
https://support.google.com/webmasters/thread/164708143/sitemap-xml-%E4%B8%8D%E8%A2%AB%E6%8A%93%E5%8F%96?hl=zh-hans
> 无法获取站点地图错误的发生原因通常是由于 Google 搜索控制台中的错误。对此没有简单的解决方法。实际上，状态是待定的，您必须等待一段时间才能返回正常状态（通常几天到几周不等）。
>  
> 你可以通过GSC中的网址检测工具进行你站点地图的网址检查，查询sitemap是否可以正常给Google抓取收录。如果显示正常，则剩下就交由Google处理，请耐心等待一段时间，我试过最长是6周。
>  
> 希望可以帮到你！

**Comment by baiyz0825** [comment]
我也出现了相同的问题，google search无法获取站点地图，使用网址检测显示
![image](https://user-images.githubusercontent.com/81071870/196038097-555691ef-f366-4452-b593-6846502ec61f.png)
![image](https://user-images.githubusercontent.com/81071870/196038113-77b9c877-e70b-4476-9502-79770eace89d.png)
![image](https://user-images.githubusercontent.com/81071870/196038117-1b89daab-ce15-4ff8-ab98-f2c235aabd5a.png)
如上图这种情况

**Comment by Drun1baby** [comment]
> 我也出现了相同的问题，google search无法获取站点地图，使用网址检测显示 ![image](https://user-images.githubusercontent.com/81071870/196038097-555691ef-f366-4452-b593-6846502ec61f.png) ![image](https://user-images.githubusercontent.com/81071870/196038113-77b9c877-e70b-4476-9502-79770eace89d.png) ![image](https://user-images.githubusercontent.com/81071870/196038117-1b89daab-ce15-4ff8-ab98-f2c235aabd5a.png) 如上图这种情况

等一段时间就可以了

**Comment by baiyz0825** [comment]
> > 我也出现了相同的问题，google search无法获取站点地图，使用网址检测显示 ![image](https://user-images.githubusercontent.com/81071870/196038097-555691ef-f366-4452-b593-6846502ec61f.png) ![image](https://user-images.githubusercontent.com/81071870/196038113-77b9c877-e70b-4476-9502-79770eace89d.png) ![image](https://user-images.githubusercontent.com/81071870/196038117-1b89daab-ce15-4ff8-ab98-f2c235aabd5a.png) 如上图这种情况
> 
> 等一段时间就可以了

ok

**Comment by RoyRao2333** [comment]
https://royrao2333.github.io/sitemap.xml

你们有没有遇到我这种，生成出来的并非是xml文件？我感觉这才是违和无法读取的真凶。

<img width="994" alt="image" src="https://user-images.githubusercontent.com/31413093/204734335-c22a4266-a5c6-45b0-9713-9f426cd1e3f0.png">
