### ISSUE TITLE
When i Changed my github username, but now the hexo sitemap still use the old username for it?

### ISSUE THREAD

**Issue by xxl4** [hexojs/hexo-generator-sitemap#158]
When i Changed my github username, but now the hexo sitemap still use the old username for it?

https://xxl4.github.io/me/sitemap.xml

![image](https://github.com/hexojs/hexo-generator-sitemap/assets/34465153/bc7eb975-f764-4a63-a6f5-ba8219b1800d)

**Comment by uiolee** [comment]
This has nothing to do with `hexo-generator-sitemap`, please check your `_config.yml`

https://hexo.io/docs/configuration#URL

**Comment by xxl4** [comment]
> This has nothing to do with `hexo-generator-sitemap`, please check your `_config.yml`
> 
> https://hexo.io/docs/configuration#URL

Thank you,i see it.
