### ISSUE TITLE
JS Files in Sitemap

### ISSUE THREAD

**Issue by joezimjs** [hexojs/hexo-generator-sitemap#16]
My repo looks something like this:

```
source
  - demos
     - demo.html
     - demo.js
```

I have some demos for my JavaScript tutorials, which include separate JS files, but since the JS files are inside the `source` directory, they're showing up in the sitemap. Can we create a whitelist/blacklist of file extensions to prevent these files from showing up?

**Comment by Xuanwo** [comment]
How about use `skip_render`?

**Comment by joezimjs** [comment]
Good idea. Never noticed that. I'll give that a try when I get a chance.

**Comment by shenqihui** [comment]
I am sorry that my pr close this issue . But I think that can solve this problem.


Like some plugin ,such as  "hexo-all-minifier",it will skip as you use skip_rander ,but I don't think it's the best solution.

Thanks
