### ISSUE TITLE
Dose sitemap include index page?

### ISSUE THREAD

**Issue by xcatliu** [hexojs/hexo-generator-sitemap#19]
Hi,

When I use this plugin to generate sitemap, it seems that the sitemap doesn't include the index page.

For example, http://js-index.com/sitemap.xml doesn't have `http://js-index.com/index.html` including.

Is it a bug or a feature?

**Comment by xcatliu** [comment]
Normally, we have only one index page which is the root page, in this case, the problem is harmless, because search engine should easily knew there is a root page.

However, I have **multi index page**, e.g. `http://js-index.com/en/index.html` and `http://js-index.com/zh-CN/index.html`, so should I add these pages to `sitemap.xml` manually? Or there is any better ideas?

**Comment by gdutxiaoxu** [comment]
When I start  the  command 'npm install hexo-generator-feed --save',it has problem,How can I do to selove this?
```
npm WARN optional dep failed, continuing fsevents@1.0.15
hexo-generator-sitemap@1.1.2 node_modules\hexo-generator-sitemap
├── object-assign@4.1.0
├── minimatch@3.0.3 (brace-expansion@1.1.6)
└── nunjucks@2.5.2 (asap@2.0.5, yargs@3.32.0, chokidar@1.6.1)
```

**Comment by xcatliu** [comment]
@gdutxiaoxu WARN can be ignored

**Comment by NoahDragon** [comment]
The index.html is ignored by default, as the `http://js-index.com/index.html` and the `http://js-index.com/` are same.

**Comment by mrttl** [comment]
Hello, I have started using this plugin but like the comments above, is there a way of removing `index.html` from the page URL within the feed?

**Comment by NoahDragon** [comment]
@mrttl Correct me if I'm wrong, I think you are talking about the https://github.com/hexojs/hexo-generator-feed

**Comment by mrttl** [comment]
hi @NoahDragon No it´s the sitemap that shows `foo/index.html`, feeds works just fine :)

**Comment by NoahDragon** [comment]
@mrttl I'm using the https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap , seems do not have this issue.

**Comment by mrttl** [comment]
@NoahDragon  that was the first one I tried but Google Webmaster Tools gives me a few warnings when it tries to use the sitemaps, so changed it for this one and passed no problems, but then I have index.html after the URL, also does not have tags or categories.

**Comment by NoahDragon** [comment]
@mrttl You are right, this plugin doesn't support tags and categories.  I think this issue relate to #1306, and it is planned to fix. Close this issue as we are off topic, please open new one if need more discuss.
