### ISSUE TITLE
On the link in the https problem

### ISSUE THREAD

**Issue by ilovesusu** [hexojs/hexo-generator-sitemap#21]
I come from China, visit github pages only through the https, but the hexo-generator-sitemap generated sitemap.xml document is only http. What should i do

see it [sitemap.xml ](https://ilovesusu.github.io/sitemap.xml)

**Comment by NoahDragon** [comment]
In your _config.yml file set your website url to https:
```yml
url: https://cn.abnerchou.me
```

**Comment by ilovesusu** [comment]
Thank you
