### ISSUE TITLE
Add categories url on sitemap

### ISSUE THREAD

**Issue by jdvr** [hexojs/hexo-generator-sitemap#23]
I have create a the pull request #20, to add support for categories on sitemap. I see it as a very helpful feature and I am using it.

It seems like the coverage on the PR has decrease, **I can add some test** if you like the feature and it will be merge.

**Comment by NoahDragon** [comment]
Great job. Please add some test to make all the CI happy. :-)

**Comment by mrttl** [comment]
@jdvr I was just wishing to add categories to the sitemap ;) can´t wait to get the latest version, will it only be categories? Or will it have tags as well?

**Comment by jdvr** [comment]
Hi!
Sorry I haven been out of home for a while. 
@NoahDragon During this month I will try to add a test. If you have a cleared idea about how to do it I will appreciate some help.

@mrttl this only ads support for categories.

**Comment by jdvr** [comment]
@NoahDragon  I have tried to insert some categories on test mock but it isnt possible. Any idea?

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-sitemap/pull/26
