### ISSUE TITLE
double slash

### ISSUE THREAD

**Issue by TrejGun** [hexojs/hexo-generator-sitemap#27]
first of all thanks for this plugin

the output is a bit inconsistent with native hexo behavior
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://localhost:4000//index.html</loc>
    <lastmod>2017-10-17T10:12:39.000Z</lastmod>
  </url>
</urlset>
```

double slash in url is caused because i have 
```yaml
url: https://localhost:4000/
```

in _config.yml file, however hexo's helper `url_for` fixes this by replacing `path.replace(/\/{2,}/g, '/')` , so ay e probably you should do this to for consistency

**Comment by NoahDragon** [comment]
We don't recommend to have the trailing slash for url. I think it is by design.

![image](https://user-images.githubusercontent.com/5704064/32509449-52df589e-c3bb-11e7-9742-f73f46fcc1c9.png)
