### ISSUE TITLE
Am I reading your code incorrectly? Conditional always false?

### ISSUE THREAD

**Issue by MegaJ** [hexojs/hexo-generator-sitemap#29]
I'm referring to

https://github.com/hexojs/hexo-generator-sitemap/blob/master/lib/template.js#L8

seems like the variable `sitemapTmpl` will always be undefined. No chance for side-effects changing the variable during normal runtime because `sitemapTmpl` is in a lexical closure. I suggest a removal of this line, unless I'm reading this wrong...

**Comment by demurgos** [comment]
`sitemapTmp1` is a module global.
It acts as a memoized variable.

It's declared outside of the function and and set on line 21:
https://github.com/hexojs/hexo-generator-sitemap/blob/a45bedd6b7c9d2f8b82bbc9702bd1ab358114ddb/lib/template.js#L21

**Comment by MegaJ** [comment]
Whoops nevermind, you're caching it in case the generator is called again during something like `hexo server`

**Comment by MegaJ** [comment]
Whoops nevermind, you're caching it in case the generator is called again during something like `hexo server`

**Comment by MegaJ** [comment]
Whoops nevermind, you're caching it in case the generator is called again during something like `hexo server`. Please close.

**Comment by MegaJ** [comment]
Whoops nevermind, you're caching it in case the generator is called again during something like `hexo server`.

I've been reading a fair number of plugins lately and sometimes I find them really specific to how hexo is run...which I would be more comfortable with if there were more documentation for the pipeline of transformations, from source posts to final rendering.

**Comment by MegaJ** [comment]
Whoops nevermind, you're caching it in case the generator is called again during something like `hexo server`.

I've been reading a fair number of plugins lately and sometimes I find them really specific to how hexo is run...which I would be more comfortable with if there were more documentation for the pipeline of transformations, from source posts to final rendering.

Please close.

**Comment by MegaJ** [comment]
Whoops nevermind, you're caching it in case the generator is called again during something like `hexo server`.

I've been reading a fair number of plugins lately and sometimes I find them really specific to how hexo is run...which I would be more comfortable with if there were more documentation for the pipeline of transformations, from source posts to final rendering.

Please close.

**Comment by demurgos** [comment]
Please use the `edit` button instead of submitting the same message with a few words changed.

**Comment by MegaJ** [comment]
I apologize, I'm having problems with github, the client side js told me I was unable to comment, but apparently commented.
