### ISSUE TITLE
exclude something from sitemap

### ISSUE THREAD

**Issue by wylyeak** [hexojs/hexo-generator-sitemap#6]
how can i exclude something from sitemap

**Comment by szarouski** [comment]
[You can do it](https://github.com/hexojs/hexo-generator-sitemap/commit/ffc40c251796142089a97a31e51695a1723979ea/lib/generator.js#diff-b58e2f1cee2acff55355343774e6d576R13) by setting `sitemap` to false in post settings. I think this answers your question and issue could be closed.

**Comment by joysboy** [comment]
This plugin generate all html files, but I want to exclude some files. These files is html originally. I can't set sitemap is false.

**Comment by weivincewang** [comment]
Same issue, for example README.md

**Comment by joezimjs** [comment]
I'm even getting some JS files in the mix. Also some permalinks have 'index.html' in them and some don't. This seems to be a Hexo issue, but can't we set something up to have index.html stripped from the end of URLs.

**Comment by leesei** [comment]
I think the original question of excluding post from sitemap can be done with `sitemap: false` front matter.

@joezimjs Could you open new issue describing your use case?
A sample repo would be even better. Thanks.
