### ISSUE TITLE
无法在windows下安装

### ISSUE THREAD

**Issue by jiankunking** [hexojs/hexo-generator-sitemap#64]
环境：win 7
操作：npm install hexo-generator-sitemap --save
错误：
```
$ npm install hexo-generator-sitemap --save  
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse vents):                                                                          
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@ 1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"} )                                                                                                                                                                 + hexo-generator-sitemap@1.2.0                                                   
added 1 package from 1 contributor, updated 1 package and audited 18296 packages  in 23.265s 
 found 3 low severity vulnerabilities                                               
run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by jiankunking** [comment]
`
hexo: 3.9.0

hexo-cli: 2.0.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
`

**Comment by YoshinoriN** [comment]
It's just a warning. 
The fsevents package is an optional dependency.

> https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by jiankunking** [comment]
> It's just a warning.
> The fsevents package is an optional dependency.
> 
> > https://docs.npmjs.com/files/package.json#optionaldependencies

明白了，谢谢回复
