### ISSUE TITLE
npm audit security report

### ISSUE THREAD

**Issue by songjiang951130** [hexojs/hexo-generator-sitemap#72]
![image](https://user-images.githubusercontent.com/20123559/66534021-89495280-eb47-11e9-978c-124fcb734091.png)

how to fix it ?

**Comment by SukkaW** [comment]
Although this vulnerability will not cause any security issue on Hexo since the plugin is run locally, but we will updates the nunjucks dependencies to latest to see if the vulnerability has been fixed.

**Comment by songjiang951130** [comment]
https://github.com/mozilla/nunjucks

the lastest version of nunjucks is v3.2.0

please try it!

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo-generator-sitemap/blob/de53fb0656b9cba85c9fb5457db39f3d6fba53eb/package.json#L34

```
"nunjucks": "^3.1.6"
```
This meant that npm will install the latest version of `nunjucks@3`
Run `npm i` or `npm audit fix` if necessary
