### ISSUE TITLE
hexo 3.0 rc4 don't support

### ISSUE THREAD

**Issue by maplewizard** [hexojs/hexo-generator-sitemap#9]
When I use hexo-generator-sitemap in hexo 3.0 rc 4, no sitemap file generate.

**Comment by tommy351** [comment]
Try hexo-generator-sitemap@1.0.0

**Comment by maplewizard** [comment]
@tommy351 I downloaded hexo-generator-sitemap and unzip it in /node_modules, and add 
plugins:
- hexo-generator-sitemap
in the config file. it still cannot creat any sitemap file. Is there anything I missed?

**Comment by tommy351** [comment]
```
$ npm install hexo-generator-sitemap@1.0.0 --save
```

**Comment by maplewizard** [comment]
Thanks it works!
