### ISSUE TITLE
Ignore the 404 page in sitemap.

### ISSUE THREAD

**Issue by mutoo** [hexojs/hexo-generator-sitemap#90]
I've built a 404 page in my template. And it's rendered as a page.

### source/404/index.md

```
---
layout: 404
title: 404 - Page not Found
comments: false
---
```

I used this page as a default 404 page in AWS S3 bucket.

But then, I found it also be referenced in the sitemap, which causes the index error inside google search console.

I've read the source, there is a `skip_render` in global site config to opt-out some files, but it's an option to disable the render rather than just ignore the pages in the sitemap.

I suggest adding a special config to opt-out pages that bloggers don't want them to be added to the sitemap.

**Comment by curbengh** [comment]
``` diff
---
layout: 404
title: 404 - Page not Found
comments: false
+sitemap: false
---
```

**Comment by SukkaW** [comment]
@curbengh Is the feature documented?

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-sitemap#excluding-posts
