### ISSUE TITLE
The generate sitemap <lastmod> is wrong(inaccuracy)!

### ISSUE THREAD

**Issue by DeppWang** [hexojs/hexo-generator-sitemap#92]
The `hexo-generator-sitemap` plugins generated sitemap.xml that `<lastmod>` corresponding the last modification time of **the source folder file**, but the `<lastmod>` should corresponding the last modification time of **the html file**.

the sitemap.xml example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> 
  <url>
    <loc>http://www.example.com/foo</loc>
    <lastmod>2018-06-04T18:00:15+00:00</lastmod> <!--The time last modification of the `foo.html`.-->
  </url>
</urlset>
```
I found [GSC Help] have a tips:
> Google reads the `<lastmod>` value, but if you misrepresent this value, we will stop reading it.
- source: [Manage your sitemaps: Build and submit a sitemap](https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190)

If the sitemap `<lastmod>` is wrong, meaning the sitemap not effect?

About [lastmod](https://www.sitemaps.org/protocol.html#lastmoddef)

----
append in 2020.04.16:

Because my sitemap cann't be read by [GSC](https://search.google.com/search-console/), I guess may be caused by the wrong `<lastmod>`.

![image](https://user-images.githubusercontent.com/21981221/79407762-5f785900-7fcc-11ea-9ffa-3e5d324ae998.png)

It cause my article cann't be indexed in time. Almost need a week!

Your sitemap can be read in GSC? Your posted article can be searchable in next day?

If your sitemap can be read, and the `<lastmod>` don't inconsistent, So the `<lastmod>` don't matter in sitemap!

If your sitemap can not be read, but your posted article can be searchable in next day. Please reply me, I need your help.

**Comment by flashlab** [comment]
you can modify sitemap.xml or create external template as your own demand. Like this:
`post.updated.toISOString().substring(0, 10)`
Hope it will help you

**Comment by SukkaW** [comment]
@flashlab @DeppWang 

If you guys are sure there is something wrong with  `lastmod`, feel free to open a new pull request.

**Comment by DeppWang** [comment]
@flashlab 
Thanks, ask a question: Your sitemap can be read in [GSC](https://search.google.com/search-console)?

**Comment by DeppWang** [comment]
@flashlab I found your article can be indexed in time. Ask a question: Your sitemap can be read in [GSC](https://search.google.com/search-console)?

**Comment by flashlab** [comment]
@DeppWang @SukkaW tested myself
Please check #94

**Comment by DeppWang** [comment]
@SukkaW I found your article can be indexed in time. Ask a question: Your sitemap can be read in GSC?

**Comment by DeppWang** [comment]
@flashlab 
May be can use a `sitemap_template.xml` replace time to date, don't need change to source code. 

![image](https://user-images.githubusercontent.com/21981221/79410922-31971280-7fd4-11ea-87de-1ed53387d571.png)

You can check your GSC, if your sitemap can be read. So the <lastmod> is not a issue.

If <lastmod> is a issue. Can't to change <lastmod> solove it, need to get html file last modification time, or remove <lastmod>.

**Comment by curbengh** [comment]
`2018-06-04T18:00:15+00:00` does conform to the W3C Datetime/ISO 8601 format as specified by the [protocol](https://www.sitemaps.org/protocol.html).

Perhaps Google expected `2018-06-04T18:00:15.000Z` which should be the format generated by this plugin.

Can I have your Node version and "package.json"? Output of `$ node -v` and `$ npm ls --depth 0`?

In the meantime, I'll check my GSC.

**Comment by DeppWang** [comment]
@curbengh , Thanks your reply.

1. `2018-06-04T18:00:15+00:00` was copied from [protocol](https://www.sitemaps.org/protocol.html). My sitemap.xml `<lastmod>` format is like `2018-06-04T18:00:15.000Z`. I didn't notcie the difference of both(a mistake). I rather express the difference between the local md file last modified time and online html file last modified time. May be the difference don't matter. My sitemap.xml: https://depp.wang/sitemap.xml. After test: Even though I remove the `<lastmod>` of sitemap.xml, the GSC also can't read my sitemap.xml.

2. I use [hexo-aciton](https://github.com/DeppWang/hexo-action/) deploy blog, this is the hexo env. I don't think it's related to env.

   ![image-20200630215737914](https://deppwang.oss-cn-beijing.aliyuncs.com/blog/2020-06-30-135738.png)

3. I first added my site to GSC in 2017. 

I guess it may be that the weight of my site is too low, so GSC does not read my sitemap.xml. Now, Google Spider should indexes my articles through the homepage, so it very slow.

Your sitemap.xml can be read in time?

**Comment by curbengh** [comment]
> My sitemap.xml: https://depp.wang/sitemap.xml

I notice all `<lastmod>` values are the same, which I think is the deployment time. Perhaps GSC finds it unusual and ignore it.

I have two suggestions (you can try all):
1. Use `post.date` only, this requires custom template.
  - Add the following content to "source/.sitemap.xml":
  ``` xml
  <?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for post in posts %}
    <url>
      <loc>{{ post.permalink | uriencode }}</loc>
      {% if post.date %}
      <lastmod>{{ post.date.toISOString().substring(0, 10) }}</lastmod>
      {% endif %}
    </url>
    {% endfor %}
  </urlset>
  ```
  - Configure this plugin to use the above sitemap:
  ``` yml
  _config.yml
  sitemap:
    template: ./source/.sitemap.xml
  ```
2. GSC also supports RSS. Install [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed) and add `https://depp.wang/atom.xml` to GSC. Do not remove sitemap from GSC.

**Comment by DeppWang** [comment]
@flashlab 
1. This step I had done. Because I use github action deploy blog, the action env will clone all files again each time. so the `lastmod` are the same. There is no good way to solve this issue.
2. I had added atom.xml to GSC, follow your suggestion. 

Thinks your suggestions.

**Comment by curbengh** [comment]
> the action env will clone all files again each time. so the `lastmod` are the same.

My suggested template doesn't use `post.updated`; it _only_ uses `post.date` (derived from a post's front matter) so "lastmod" should be unique.

**Comment by DeppWang** [comment]
I didn't notice the details, I have updated it. 

Thanks very much!

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-sitemap/pull/94, released in [2.1.0](https://github.com/hexojs/hexo-generator-sitemap/releases/tag/2.1.0).

**Comment by DeppWang** [comment]
@curbengh Hi, I am coming again 😂, same old problem.  [atom.xml](https://depp.wang/atom.xml) still "Coun't fetch" . 

![image](https://user-images.githubusercontent.com/21981221/89386201-535b0780-d733-11ea-8d35-3f36cb122de5.png)

GSC [said](https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190&authuser=0#:~:text=Google%20accepts%20RSS%202.0%20and%20Atom%201.0%20feeds.) they can use the Atom 1.0 or RSS 2.0 as a sitemap, My [atom.xml](https://depp.wang/atom.xml)  is Atom 1.0,  I check the [format](https://en.wikipedia.org/wiki/Atom_(Web_standard)) is right. It is possible that I use the Cloudfare as a DNS causing it? I have no idea. I try to feedback to google support, but no reply. 

What direction shou I take to check for error? Can you give me a suggestion, thx.

**Comment by curbengh** [comment]
I use Cloudflare as well and my atom.xml issue resolved itself within a few days. Can you access to `http://yoursite.com/atom.xml.gz`? Alternative is to switch to RSS format and try again.

**Comment by DeppWang** [comment]
My `https://depp.wang/atom.xml.gz` can't access, your site atom.xml.gz can download the xml. I will try to use the RSS, hope it can useful. Thanks for your reply.
