### ISSUE TITLE
Solution to sitemap submission failure (displaying "HTTP")

### ISSUE THREAD

**Issue by AimTao** [hexojs/hexo-generator-sitemap#93]
## Error
「google」Submit the sitemap as follows:

![error](https://user-images.githubusercontent.com/46548984/78634657-01b28580-78d7-11ea-8b7b-b5dd2f4dfc7f.png)
    
## Solution
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> 
  <url>
    <loc>http://www.example.com/page</loc>
    <lastmod>2018-06-04T18:00:15+00:00</lastmod> 
  </url>
</urlset>
```
Remove the time after the date to submit successfully。
After modification, it changes to the following：
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> 
  <url>
    <loc>http://www.example.com/page</loc>
    <lastmod>2018-06-04</lastmod> 
  </url>
</urlset>
```

**Comment by tuananh** [comment]
it's weird. my sitemap looks the same and it's valid. 

```xml
<lastmod>2013-07-19T22:39:00+07:00</lastmod>
```

**Comment by stevenjoezhang** [comment]
The error message provided by google does not match the solution you made. The issue may be caused by other reasons.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-sitemap/pull/94 removes the time after date.
