### ISSUE TITLE
google文件格式不符

### ISSUE THREAD

**Issue by silmont2000** [hexojs/hexo-generator-sitemap#95]
检查了一下，生成的xml里面缺少了：
`<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"> ...</urlset>`
希望早日更新！

**Comment by Arch1tect** [comment]
提交给google后得到的错误：

This url is not allowed for a Sitemap at this location.
Examples
URL:
http://yoursite.com/2020/01/07/travel-with-strangers/
Line 4
URL:
http://yoursite.com/2019/10/07/joker/
Line 11

**Comment by curbengh** [comment]
> 生成的xml里面缺少了：
> `<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"> ...</urlset>`

It has always been there? https://github.com/hexojs/hexo-generator-sitemap/blob/c9c2d90959668346da88d5193c109dbc107476a4/sitemap.xml#L2

**Comment by uiolee** [comment]
I cannot reproduced your case and no one provides enough information, I am going to **close** this issue. 

If the problem still exists, please **reopen** this issue and provide more information.
